# Generated by Django 6.0.7 on 2026-07-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0003_restaurant_location_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
