# Generated by Django 6.0.7 on 2026-07-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0004_alter_restaurant_contact_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="price_full",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="price_half",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
