# Generated by Django 6.0.7 on 2026-07-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0005_menuitem_price_full_menuitem_price_half'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price_tiers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
