# Generated by Django 6.0.7 on 2026-07-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0006_menuitem_price_tiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="photo",
            field=models.URLField(blank=True),
        ),
    ]
