# Generated by Django 6.0.7 on 2026-07-23 19:09

import django.db.models.deletion
import outlets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0007_location_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_code",
                    models.CharField(
                        default=outlets.models.generate_order_code,
                        editable=False,
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("student_uid", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("payment_pending", "Payment pending"),
                            ("placed", "Placed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("ready", "Ready for pickup"),
                            ("completed", "Completed"),
                        ],
                        default="payment_pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("razorpay_order_id", models.CharField(blank=True, max_length=64)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=64)),
                ("razorpay_refund_id", models.CharField(blank=True, max_length=64)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("estimated_ready_minutes", models.PositiveIntegerField(default=15)),
                ("estimated_ready_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="outlets.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("size_label", models.CharField(blank=True, max_length=30)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="outlets.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="outlets.order",
                    ),
                ),
            ],
        ),
    ]
