# Generated by Django 6.0.7 on 2026-07-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0009_remove_order_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_claimed_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_confirmed_at",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="upi_id",
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_refund_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("payment_pending", "Payment pending"),
                    ("placed", "Placed"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("ready", "Ready for pickup"),
                    ("completed", "Completed"),
                ],
                default="payment_pending",
                max_length=20,
            ),
        ),
    ]
