# Generated by Django 6.0.7 on 2026-07-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0010_remove_order_payment_claimed_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="razorpay_refund_id",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="upi_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("claimed", "Claimed by student"),
                    ("confirmed", "Confirmed by restaurant"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("placed", "Placed"),
                    ("accepted", "Accepted"),
                    ("preparing", "Preparing"),
                    ("rejected", "Rejected"),
                    ("ready", "Ready for pickup"),
                    ("completed", "Completed"),
                ],
                default="placed",
                max_length=20,
            ),
        ),
    ]
