# Generated by Django 6.0.7 on 2026-07-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0011_remove_order_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_confirmed_at",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("claimed", "Claimed by student")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("placed", "Placed"),
                    ("preparing", "Preparing"),
                    ("rejected", "Rejected"),
                    ("ready", "Ready for pickup"),
                    ("completed", "Completed"),
                ],
                default="placed",
                max_length=20,
            ),
        ),
    ]
