# Generated by Django 6.0.7 on 2026-07-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0012_remove_order_payment_confirmed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="student_photo",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="estimated_ready_minutes",
            field=models.PositiveIntegerField(default=12),
        ),
    ]
