# Generated by Django 6.0.7 on 2026-08-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0013_order_student_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="student_upi_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
