# Generated by Django 6.0.7 on 2026-08-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0014_order_student_upi_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="student_photo",
        ),
        migrations.RemoveField(
            model_name="order",
            name="student_uid",
        ),
    ]
