# Generated by Django 6.0.7 on 2026-08-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0015_remove_order_student_photo_remove_order_student_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="student_upi_id",
        ),
        migrations.AddField(
            model_name="order",
            name="student_phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
