# Generated by Django 6.0.7 on 2026-08-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0016_remove_order_student_upi_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
