# Generated by Django 6.0.7 on 2026-08-07 12:08

from django.db import migrations, models


def rename_claimed_to_paid(apps, schema_editor):
    """Old rows used payment_status='claimed' (the self-reported "I've
    paid" flow this migration replaces) — carry them forward as 'paid' so
    existing order history stays consistent with the new choices."""
    Order = apps.get_model("outlets", "Order")
    Order.objects.filter(payment_status="claimed").update(payment_status="paid")


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0017_order_scheduled_for"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_claimed_at",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_refund_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(rename_claimed_to_paid, migrations.RunPython.noop),
    ]
