# Generated by Django 6.0.7 on 2026-08-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0018_remove_order_payment_claimed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
