# Generated by Django 6.0.7 on 2026-08-15 16:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0021_restaurantpushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="platform_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
    ]
