# Generated by Django 6.0.7 on 2026-08-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0023_emailotp_order_student_studentprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="bypass_business_hours",
            field=models.BooleanField(default=False),
        ),
    ]
