# Generated by Django 6.0.7 on 2026-08-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0024_restaurant_bypass_business_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="special_instructions",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
