# Generated by Django 6.0.7 on 2026-08-29 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0025_order_special_instructions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["email", "-created_at"], name="outlets_ema_email_fd1982_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["razorpay_order_id"], name="outlets_ord_razorpa_7a3595_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["student", "-created_at"], name="outlets_ord_student_ef03a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant", "-created_at"],
                name="outlets_ord_restaur_6f5d42_idx",
            ),
        ),
    ]
