# Generated by Django 6.0.7 on 2026-09-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0026_alter_emailotp_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_declined',
            field=models.BooleanField(default=False),
        ),
    ]
