# Generated by Django 6.0.7 on 2026-09-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0028_studentpushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
