"""
Django settings for cufr project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No default here on purpose: a missing DJANGO_SECRET_KEY should fail
# loudly at startup rather than silently fall back to a key that's sitting
# in source history.
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# Render sets this automatically to the service's *.onrender.com domain.
RENDER_EXTERNAL_HOSTNAME = env("RENDER_EXTERNAL_HOSTNAME", default=None)
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "outlets",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cufr.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cufr.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL")
}
# Without this, Django opens a brand new TCP+TLS connection to Supabase
# (a different network hop from Render) on every single request and tears
# it down at the end — that handshake cost was likely the single biggest
# contributor to "everything feels slow", more than query count or payload
# size. Reusing the connection for 60s cuts that out of most requests.
# CONN_HEALTH_CHECKS pairs with it so a connection that went stale during
# its 60s (network blip, Supabase-side timeout) gets detected and replaced
# instead of failing the request.
DATABASES["default"]["CONN_MAX_AGE"] = 60
DATABASES["default"]["CONN_HEALTH_CHECKS"] = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Django REST Framework

REST_FRAMEWORK = {
    # Token, not session+CSRF: the frontend (Vercel) and backend (Render)
    # are different domains, so JS on the frontend can never read a CSRF
    # cookie the backend set (cookies are scoped to the domain that set
    # them — SameSite doesn't change that). That silently 403'd every
    # owner-authenticated PATCH/POST (toggle item, accept/reject order,
    # etc.) while GETs still worked, since only mutations need the
    # cross-domain-unreadable CSRF token. A bearer token sent as a normal
    # header has no such cross-domain cookie dependency.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # Applied to LoginView via throttle_scope = "login" — slows down
        # brute-force password guessing without needing a new dependency.
        "login": "5/min",
        # Applied to order create/verify/lookup — keeps genuine ordering
        # snappy while making order-code enumeration impractical.
        "orders": "30/min",
    },
}


# CORS / CSRF (frontend runs on a different local port during development)

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:5500",
        "http://127.0.0.1:5500",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8080",
        "http://127.0.0.1:8080",
    ],
)
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "http://localhost:5500",
        "http://127.0.0.1:5500",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8080",
        "http://127.0.0.1:8080",
    ],
)
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")


# Razorpay — students pay into this account (the platform's own), not each
# restaurant's UPI ID directly. See CreateOrderView / RazorpayWebhookView in
# outlets/views.py for the actual flow. Use rzp_test_* keys while developing;
# swap to live keys only once the webhook is verified end-to-end.
RAZORPAY_KEY_ID = env.str("RAZORPAY_KEY_ID", default="")
RAZORPAY_KEY_SECRET = env.str("RAZORPAY_KEY_SECRET", default="")
# Configured separately in the Razorpay dashboard under the webhook you
# create there — not the same as the API key secret above.
RAZORPAY_WEBHOOK_SECRET = env.str("RAZORPAY_WEBHOOK_SECRET", default="")


# Web Push — lets order-status.html and the dashboard notify a device even
# when the app/tab isn't open, unlike the plain browser Notification API
# used elsewhere which only fires while the page is loaded. VAPID_PUBLIC_KEY
# is safe to expose (it's what the frontend uses to subscribe); the private
# key must never leave the backend. See outlets/views.py send_order_push().
VAPID_PUBLIC_KEY = env.str(
    "VAPID_PUBLIC_KEY",
    default="BOsXYYIQK2rY1nET_I-NXr-A6ts9_WDH9kEjZYBUC7mGhcfLqRLy3jbXtD3X72WZU1gaAqI_yOz8pO_6FNhhHqo",
)

# PEM keys are multi-line; stored in .env / Render's env editor as a single
# line with literal \n escapes (both are single-line-only), unescaped here.
_vapid_private_key_raw = env.str("VAPID_PRIVATE_KEY", default="")
VAPID_PRIVATE_KEY = _vapid_private_key_raw.replace("\\n", "\n")
VAPID_CLAIM_EMAIL = env.str("VAPID_CLAIM_EMAIL", default="mailto:admin@cufood.app")


# Production hardening (only applies when DEBUG=False, i.e. on Render)

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # The frontend (Vercel) and this backend (Render) are on different
    # domains, so owner login is a cross-site request. Django's default
    # SameSite=Lax cookies are dropped by the browser on cross-site
    # fetch/XHR calls (only same-site or top-level link navigation are
    # allowed), which breaks the session right after a successful login —
    # "None" explicitly allows it. Requires Secure=True (above), which is
    # already true since both sides are HTTPS.
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SAMESITE = "None"
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
